### ISSUE TITLE
Update to Bootstrap v4 Alpha 6

### ISSUE THREAD

**Issue by coliff** [Rundiz/bootstrap-basic4#5]

**Comment by ve3** [comment]
Updated.
I'm not sure is all working good.
If everything works fine then I will update the new version to wordpress.org but they still do not approve this theme.

ps. I'm too tired to update Bootstrap 4 in [bootstrap4-basic-template](https://github.com/Rundiz/bootstrap4-basic-template) 😅😛 because they changes too many thing and there is no changed guideline. I think I will wait until they release the full version (for [bootstrap4-basic-template](https://github.com/Rundiz/bootstrap4-basic-template)).

**Comment by ve3** [comment]
https://themes.trac.wordpress.org/ticket/38854
